
services:
  nginx:
    build: requirments/nginx
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/wwww/wordpress
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: always
  mariadb:
    build: requirments/mariadb
    networks:
      - inception
    ports:
      - '3306:3306'
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    restart: always
  wordpress:
    build: requirments/wordpress
    networks:
      - inception
    ports:
      - '9000:9000'
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/nolan/Data/wordpress'
  mariadb:
    driver: 'local'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/nolan/Data/mariadb'

networks:
  inception:
    driver: bridge
